package s3

// Operation ...
type Operation string

const (
	// CreateBucket ...
	CreateBucket Operation = "CreateBucket"
	// PutObject ...
	PutObject Operation = "PutObject"
	// GetObject ...
	GetObject Operation = "GetObject"
	// DeleteObject ...
	DeleteObject Operation = "DeleteObject"
	// DeleteBucket ...
	DeleteBucket Operation = "DeleteBucket"
)
